### ISSUE TITLE
Dwemer blocks uncraftable if Botania is installed

### ISSUE THREAD

**Issue by nihiltres** [ferreusveritas/Cathedral#1]
I added Cathedral to my pack to test it (and look at its blocks, since there's no preview images yet) but found that I could not craft the Dwemer blocks. No crafting recipe shows up in JEI (the chiselling recipes work fine).

I checked the code, and found the recipe as registered in [Dwemer.java](https://github.com/ferreusveritas/Cathedral/blob/master/src/main/java/com/ferreusveritas/cathedral/features/dwemer/Dwemer.java): eight basalt surrounding a metal ingot. AFAICT my pack does not include any items dictionaried as `ingotDwemer`, `ingotDawnstone`, `ingotBronze`, or `ingotBrass`, so the fallback is presumably the basic `ingotGold`. I double-checked that the gold-ingot recipe doesn't work by putting it into the crafting table anyway (in case it was just JEI missing it) but it also failed.

My pack does not contain any mods from the Thermal series, but it does contain some other mods that might themselves include compatibility code for some of the referenced metals; IIRC molten bronze for Tinker's Construct exists despite neither bronze nor tin being added by any extant mod—it may be a multi-mod compatibility issue.

I'll try to help narrow down the issue by copying my pack to a new instance and whittling down the modlist to the mods necessary to duplicate it.

**Comment by ferreusveritas** [comment]
That is interesting actually.  I wonder why nihiltres is having a problem then.

**Comment by ferreusveritas** [comment]
I'm unable to reproduce this problem.  I ran the mod with only Cathedral, CTM, Chisel, and JEI and I can craft the Dwemer block with a gold ingot.  You might want to double check and try again otherwise I'm afraid you'll need to find the origin of the problem yourself and report back with new information.

**Comment by erindalc** [comment]
So that...initializes an ore dict entry, making the mod think there's brass when there actually isn't?

**Comment by ferreusveritas** [comment]
I don't think there's much I can do about this.  Other mods expecting ingotBrass to work(which should be a reasonable expectation) would also be broken by Botania.

**Comment by williewillus** [comment]
I'm going to hot potato this one over to Forge. Botania is simply using the forge json ore dict ingredient format, so there's nothing really we can do to fix it. the *real* bug is forge creating empty entries from these ingredients.

**Comment by ferreusveritas** [comment]
I can give it a shot if it will expedite getting this out of way.

**Comment by ferreusveritas** [comment]
I added code to check if the ore list is empty.

**Comment by AshenGaming** [comment]
Any chance this fix will be uploaded soon? 

As a temporary fix I just used a crafttweaker script to add the recipe back in, but it would be nicer if it worked out the box. No rush of course, just wondering if it'll be updated soon :)
