### ISSUE TITLE
Holes on top of panels

### ISSUE THREAD

**Issue by LemADEC** [ferreusveritas/Cathedral#11]
As of 1.12.2-1.9.7k, the top side of panels have holes / missing faces depending on what block is placed above:
![image](https://user-images.githubusercontent.com/4776032/59950808-5df70680-9477-11e9-9e5e-db8912cd6ec0.png)

**Comment by ferreusveritas** [comment]
Unfortunately this is necessary in order for the glass panes to not have bars in them and destroy the continuous effect.

**Comment by LemADEC** [comment]
I don't see why your mod wouldn't be able to do what other mods did in the past.

**Comment by ferreusveritas** [comment]
Show me

**Comment by LemADEC** [comment]
![image](https://user-images.githubusercontent.com/4776032/77252377-cd429680-6c53-11ea-802f-13c2dfe2f041.png)
Vanilla panel on top, WarpDrive omnipanel on bottom

**Comment by ferreusveritas** [comment]
Yes.  It makes a horizontal bar on the interior of the glass like that.  Which is what I was trying to avoid.  I don't know a way around it at the moment.

**Comment by LemADEC** [comment]
that extra horizontal bar is fairly minor compared to missing it completely
