### ISSUE TITLE
Client crash when using Exchanger from Building Gadgets

### ISSUE THREAD

**Issue by LemADEC** [ferreusveritas/Cathedral#13]
Forge version 14.23.5.2838
Building Gadgets version 2.6.8
Cathedral version 1.12.2-1.9.7k
https://gist.github.com/LemADEC/62ac8e96d130ae69dd4924b5b7c3079f

** How to reproduce the issue
Get an Building Gadgets mod's Exchanger and set it to the Cathedral mod's Dwarven pillar
Trying to use it or change it causes a crash

As reported initially here: https://github.com/Direwolf20-MC/BuildingGadgets/issues/323

**Comment by ferreusveritas** [comment]
Recipe fixed
