### ISSUE TITLE
[Bug] Dwarven Bars show up with normal Iron Bar texture when placed.

### ISSUE THREAD

**Issue by AnotherVagabond** [ferreusveritas/Cathedral#15]
https://imgur.com/a/5vpF7b4

**Comment by linkovich** [comment]
Having this issue as well :(

**Comment by linkovich** [comment]
Just realized you and I were using the same texture pack. This happens with the unity texture pack installed. I removed the pack and it works fine. There may be some workaround using resource loader

**Comment by linkovich** [comment]
For the mod author: to fix this you just need to include a copy of the original model and reference that rather than the existing one, in case resource packs overwrite it.

For the rest of us: Same thing, but use resource loader to overwrite Cathedral's files.
