### ISSUE TITLE
Missing blocks shown in images

### ISSUE THREAD

**Issue by IdrisQe** [ferreusveritas/Cathedral#4]
I notice a few missing blocks in the pictures on the mod page that are not actually included. In the "crafting hall", "deep village",and "Morian pillars" images there are small flat lights and hanging Dwemer-style lamps, neither of which appear to be in the mod currently. Additionally in the "storage silos" picture, there's what appears to be horizontal metal panes, when neither horizontal nor vertical metal panes are even in the mod (there are fences which match the Ornate Metal but not the normal Dwemer Metal).

I'm not sure if these are the result of another mod, or simply not included in the current release, but it would be appreciated if that were cleared up.

**Comment by ferreusveritas** [comment]
The thin plates and flat lights are microblocks.  The hanging lamps are from project red.  I took these pictures back when the mod was running in 1.7.10.  Microblocks for 1.12.2 has gotten kinda weird and doesn't apply universally anymore so you can't automatically have the ability to cut the blocks with a saw.  I do plan to add dwarvish catwalks in time though.  They would be much like the horizontal metal grates only with hand rails.  I also plan to add compatibility with forge microblocks when I get a chance so these features can be created again.

**Comment by LemADEC** [comment]
LittleTiles is a good alternative to Microblocks, give it a try :)

**Comment by IdrisQe** [comment]
Oh cripes, this is still open? This wasnt even an issue in the first place. Oops.
But yeah LittleTiles does look very nice too. I've always been a bit wary of microblock mods in general due to implied lag but ah...

**Comment by LemADEC** [comment]
For the record, LittleTiles and BlockCraftery are fairly optimized on 1.12.2, nowhere close to the lag you may have experience with Microblocks or CarpentersBlocks on 1.7.10.
