### ISSUE TITLE
Miscellaneous Suggestions and Additions

### ISSUE THREAD

**Issue by IdrisQe** [ferreusveritas/Cathedral#5]
While I'm not sure you want to expand more on the contents of the mod, I have a few suggestions:

-Perhaps add stair and slab variants for each basalt block type (some are already included), also Dwemer Metal Panel stairs/slabs.

-Some more decorations to go with the Dwemer stuff would be great! In particular, modelled gaslamps with little blue flame particles that can be hung from chains, roofs, or on walls would be brilliant. Maybe also some Dwemer variants of vanilla mechanical blocks like Furnaces, Pistons, Hoppers, Droppers, Dispensers, Levers, etc. Perhaps a few simple automaton or head statues since personally I don't find the metal Gargoyles quite fit the style these blocks are going for.

-More types of stained glass would always be appreciated, though I can understand these may be difficult to design well.

-Trapdoors! Maybe even 1x2 or 2x2 trapdoors. Also variants for them and the doors which can only be opened with redstone would be a nice touch.

-Also perhaps go over the metal textures for some of the Dwemer stuff again. The blocks are beautiful already, but things like the carvings and doors and railings and panels and a few of the blocks like chains, etc. seem to have significantly less of a "metal" appearance than the fences and metal window blocks and the scale pillar, etc. It's either a color or shading difference, maybe both, it's hard to tell. The difference is admittedly kind of distracting to a stickler for details such as myself.

I know I went kind of overboard with the Dwemer suggestions. Honestly I feel like you could flesh it out into its own entirely Dwemer-Themed decoration and mechanical mod. Maybe even with creating automatons or such. I can imagine that with Embers compatability or something and that would just be positively amazing.
That said, one last suggestion- calling this stuff Dwemer may be a bad idea. Bethesda really doesn't like people using their names. Renaming to "Dwarven" would probably be a safer idea. (Not that I don't appreciate another fan of the long-lost Deep Folk of The Elder Scrolls and their architecture, devices, and style.)

**Comment by ferreusveritas** [comment]
The mod is in alpha and was until recently only ran on a private server.  Changes are already planned to remove the dwemer name completely as I'm well aware of Bethesda and how they behave.  The curseforge page doesn't even refer to the blocks as "Dwemer" and instead uses "Dwarven".  I appreciate the suggestions and may make some gas lights like you suggested.  I also intend to make more gargoyles and adjust the color palette for the metallics in the mod as they're imperfect.  Plus adding pinnacles, churchbells, candle racks, more stained glass, cathedral style pillars and whatever else.  Not too keen on furnaces and pistons though as this is a decoration mod.
