### ISSUE TITLE
[Bug] Deck Prism and Connected Texture blcok, or block with special model

### ISSUE THREAD

**Issue by drakray** [ferreusveritas/Cathedral#9]
Using DeckPrisn on block with ConTex, like the Dwemer Pillar, make the block use the full CT Texture
![2019-02-04_22 29 13](https://user-images.githubusercontent.com/4303126/52251795-f4fa6200-28cc-11e9-917e-59d811f14252.png)

Using DeckPrism on 3D Pillar make them invisible with a CCL error message([InLogs relevant stuff](https://pastebin.com/RNT826QY))

**Comment by Cronosus** [comment]
same problem, it makes this
![obrazek](https://user-images.githubusercontent.com/5349950/56207533-4ce0e200-604f-11e9-9523-f6ce8fc785f4.png)

**Comment by DWX12** [comment]
Can confirm. Seems to mainly be pillars when prisms are applied to them.

**Comment by ferreusveritas** [comment]
Fixed by preventing deck prisms being used on pillars
